#!/usr/bin/env php
<?php
echo '';
echo 'hello', PHP_EOL;


//$birthDate = '1980-09-05';

$opts = getopt("b:");

$birthDate = $opts["b"] ?? '1980-05-04';
$todayDate = date('Y-m-d');

$birthTime = strtotime($birthDate);
$todayTime = strtotime($todayDate);

$totalSecs = $todayTime - $birthTime;
$totalDays = floor($totalSecs / 3600 / 24);

echo '', PHP_EOL;
echo "$birthDate : $totalDays", PHP_EOL;
