#!/usr/bin/env php
<?php

include './src/Dates/BirthDays.php';
$opts = getopt("b:");


echo PHP_EOL, 'start the script', PHP_EOL;
$birthDate = $opts["b"] ?? '1980-05-04';

$days = new \Berezovskiy\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo PHP_EOL, " С $birthDate прошло $totalDays дней", PHP_EOL;
