#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';
$opts = getopt("b:");


echo PHP_EOL, 'start the script', PHP_EOL;
$birthDate = $opts["b"] ?? '1980-09-05';

$days = new \Berezovskiy\Dates\BirthDays($birthDate);
$totalDays = $days->findTotalDays();

echo PHP_EOL, " С $birthDate прошло $totalDays дней", PHP_EOL;
